### ISSUE TITLE
Post Title is shown the same in Multiple Language Translet

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-multilang#78]
Post Titlle is shown the same in Multiple Language Translet

Ref video: https://www.loom.com/share/8881c07a9ad24e09826db110007928d3 

Ref ticket: https://magazine3.in/conversation/276409?folder_id=29

**Comment by saddy001** [comment]
Same here. These are the details for reproduction:

1. Create 2 new languages (now you have 3)
2. Edit the Home Page in default language (Should have title in default language, e.g. "Lang 1"), Save
3. Switch to language 2
4. Change the title to "Lang 2", Save
5. Switch to language 3
6. Change the title to "Lang 3", Save
7. Switch back to language 2
8. Bug: Title is back to default title again ("Lang 1")

This bug is a show-stopper right now ;-)

**Comment by saddy001** [comment]
PS: This bug also affects pages.

**Comment by saddy001** [comment]
PPS: This also affects the **Yoast "SEO title"** and the **Featured image caption** of posts.
