### ISSUE TITLE
Multilingual tags don't work

### ISSUE THREAD

**Issue by saddy001** [ahmedkaludi/wp-multilang#81]
When adding tags in another than the default language, the default language tags appear empty.

How to reproduce:

1. Create at least 3 languages
2. Assign tags to a post in the default language -> Save
3. Assign some other tags to a post in another language -> Save
4. Switch back to the default language
5. Bug: Tags are empty

**Comment by shridhamdeveloper** [comment]
Hi,

Thank you for reporting the bug

We tested the same at our end, but tags are not getting blank for any of the languages. The  tags are that are saved for the last language are getting applied to all the languages.

Please let us know how you are assigning the tags. Are you creating the post on Gutenberg editor of classic editor, and which theme you are using on your end. Please help us with these details so that we can recreate the same issue at our and get it resolved for you.

Do you want to assign different different tags for all the languages?

**Comment by saddy001** [comment]
> how you are assigning the tags

I assign them directly on the edit post page, on the right side

> Are you creating the post on Gutenberg editor

I use the new block editor

> which theme

Twenty Twenty-Four

> Do you want to assign different different tags for all the languages?

Yes

**Comment by shridhamdeveloper** [comment]
Hi @saddy001 ,

I request you to kindly update the plugin to latest and test, as we tested tags are not getting blank for any of the languages. if you still face the same issue then please let us know.

You can assign the translated tags according to respective languages, you can see that the tag label is translated to respective languages on post editor page. So if you requirement is to change the label of tags based on the language so you can do that, why need to assign the different tags for different languages.

Assigning different tags for all the language is not a good scenario, it may create problems for fetching the tag details on posts.

Kindly update the plugin to latest version and let us know.
