### ISSUE TITLE
How is this version different from this one here...

### ISSUE THREAD

**Issue by Anticosti** [ahmedkaludi/wp-multilang#9]
Greetings,

Huge thanks for keeping WP Multilang alive.
I use it since many years and still love it. It's lightweight and no bloat.
I am not very familiar with the GitHub language

My question is:
How's your version (2.4.2) is different from this one here ?:
https://github.com/VaLeXaR/wp-multilang/pull/194

Kindly,

**Comment by ahmedkaludi** [comment]
Thanks @Anticosti for the appreciation. We want to listen to the users, improve this and make this as a Number ONE Multi Lang plugin.

so that VaLeXaR had too many unattended issues and PR requests which is not helpful now, so we intend to start with fresh perspective and listen to each user one by one.

**Comment by Anticosti** [comment]
You guys are the ones behind PWA for WP, which I really enjoy and appreciate ? This is great news !!!
Thanks so much for continuing Valentyn Riaboshtan (VaLeXaR) legacy. 🙏🏻❤️

**Comment by Anticosti** [comment]
I am using WP Multilang in combo with Classic Editor and Breakdance Builder with some snippets that Valentyn created for me, and... pure pleasure to use. No issues.
Site: 
https://iroutier.com
(not launched yet)

**Comment by Sanjeevsetu** [comment]
Hi @Anticosti 

Thank you so much for using the plugin. We will improve it more in coming updates. I am closing this ticket as there is nothing to do in it. If You face any other issues just create new issues.
